# For explanation of the config: https://hyperledger-fabric-ca.readthedocs.io/en/release-1.4/serverconfig.html
# Keep an eye on: https://jira.hyperledger.org/browse/FABN-1234

version: 1.0.0
port: 7131
debug: false
crlsizelimit: 512000

crl:
  expiry: 24h

registry:
  maxenrollments: -1
  identities:
    - name: registrar-ca-intermediate
      pass: password
      type: client
      affiliation:
      attrs:
        hf.Registrar.Roles: "admin,peer,orderer,client,user"
        hf.Registrar.DelegateRoles: "peer,orderer,client,user"
        hf.Revoker: true
        hf.IntermediateCA: true
        hf.GenCRL: true
        hf.Registrar.Attributes: "*"
        hf.AffiliationMgr: true

db:
  type: postgres
  tls:
    enabled: false

ldap:
  enabled: false

signing:
  default:
    usage:
      - digital signature
    expiry: 8760h
  profiles:
    ca:
      usage:
        - cert sign
        - crl sign
      expiry: 43800h
      caconstraint:
        isca: true
        maxpathlen: 1
    tls:
      usage:
        - signing
        - key encipherment
        - server auth
        - client auth
        - key agreement
      expiry: 8760h

csr:
  names:
    - C: EU
      ST: "Amsterdam"
      L: "Amsterdam"
      O: hyperledger
      OU: fabric
  hosts:
    - localhost
  ca:
    expiry: 131400h
    pathlength: 1

idemix:
  rhpoolsize: 1000
  nonceexpiration: 15s
  noncesweepinterval: 15m

bccsp:
  default: SW
  sw:
    hash: SHA2
    security: 256
    filekeystore:
      keystore: msp/keystore

cfg:
  identities:
    passwordattempts: 10